version: 2.1
executors:
  go-executor:
    docker:
      - image: arangodboasis/golang-ci:latestth
  go-arango-executor:
    docker:
      - image: arangodboasis/golang-ci:latest
      - image: arangodb:3.4
        environment:
          ARANGO_NO_AUTH: "1"
jobs:
  build:
    parameters:
      push_docker_image:
        type: boolean
        default: true
      update_modules:
        type: boolean
        default: false
    executor: go-arango-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: cp go.sum go.sum.orig
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum.orig" }}
      - run: |
          go get
          make bootstrap
      - when:
          condition: <<parameters.update_modules>>
          steps:
            - run: |    
                make update-modules
      - run: |
          make all docker
      - run: |
          make test
      - store_test_results:
          path: bin/test/
      - store_artifacts: # upload test summary for display in Artifacts
          path: bin/test/
          destination: raw-test-output
      - when:
          condition: <<parameters.push_docker_image>>
          steps:
            - deploy:
                name: Push docker image
                command: |
                  echo "$DOCKER_REGISTRY_PASSWORD" | base64 -d | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY_HOST"
                  make docker-push
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.orig" }}
          paths:
            - "/go/pkg/mod"

  deploy-staging:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: cp go.sum go.sum.orig
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum.orig" }}
      - run: |
          make bootstrap
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.orig" }}
          paths:
            - "/go/pkg/mod"
      - deploy:
          name: Update docker image tag in config/controlplane
          command: |
            zutano deploy controlplane --name=datad

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: gcr
          filters:
            tags:
              only: /.*/
      - deploy-staging:
          context: gcr
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
  nightly:
    triggers:
      - schedule:
          cron: "40 3 * * *" # format: <minute> <hour> <day-month> <month> <day-week> -- so every day at 03:40 
          filters:
            branches:
              only: master
    jobs:     
      - build:
          context: gcr
          push_docker_image: false
          update_modules: true
